# frozen_string_literal: true

# DO NOT EDIT! THIS FILE IS AUTOMATICALLY GENERATED BY INFRAD

set :user,        "ldapr"
set :deploy_to,   "/home/rails/apps/ldapr"
set :repo_url,    "git@github.com:ifad/ldapr.git"
set :tmp_dir,     "#{fetch(:deploy_to)}/tmp"
set :ssh_options, { forward_agent: true, auth_methods: %w[publickey] }

append :linked_dirs, 'tmp'

role :app, ["ruby-appsrv1.ifad.org"], user: fetch(:user)

role :web, ["ruby-appsrv1.ifad.org"], user: fetch(:user)

role :db, "ruby-appsrv1.ifad.org", user: fetch(:user), primary: true

